# Generated by Django 4.1 on 2023-01-08 13:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='receta',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
