# Generated by Django 4.1 on 2023-01-09 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(max_length=5000)),
                ('tiempo', models.DateField(auto_now_add=True)),
                ('enviar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enviar', to=settings.AUTH_USER_MODEL)),
                ('recibir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibir', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
