# Generated by Django 4.1 on 2023-01-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='mensaje',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='tiempo',
            field=models.DateField(),
        ),
    ]
