# Generated by Django 4.1 on 2023-01-10 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mensajes', '0003_rename_recibir_mensajes_destinatario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='destinatario',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='recibir', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='enviar_a',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='enviar', to=settings.AUTH_USER_MODEL),
        ),
    ]
