# Generated by Django 4.1 on 2023-01-11 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0004_alter_mensajes_destinatario_alter_mensajes_enviar_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajes',
            old_name='destinatario',
            new_name='remitente',
        ),
    ]
